import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import GlobalProvider from "../components/providers/globalProvider";
import useSocket from "@/utils/useSocket";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// newwer fonts
const redHatMono = localFont({
  src: [
    {
      path: "./assets/fonts/RedHatMono-VariableFont_wght.ttf",
      weight: "100 900", // adjust as needed
      style: "normal",
    },
    {
      path: "./assets/fonts/RedHatMono-Italic-VariableFont_wght.ttf",
      weight: "100 900",
      style: "italic",
    },
  ],
  variable: "--font-red-hat-mono",
  display: "swap",
});

const bricolageGrotesque = localFont({
  src: "./assets/fonts/BricolageGrotesque-VariableFont_opsz,wdth,wght.ttf",
  variable: "--font-bricolage-grotesque",
  display: "swap",
});

const antonSC = localFont({
  src: "./assets/fonts/AntonSC-Regular.ttf",
  variable: "--font-anton-sc",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${redHatMono.variable} ${bricolageGrotesque.variable} ${antonSC.variable} antialiased dark min-h-screen`}
      >
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
